# Generated by Django 4.0.1 on 2022-01-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hostInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=30, verbose_name='IP')),
                ('zone', models.CharField(default='', max_length=30, verbose_name='区域')),
                ('status', models.IntegerField(default='', max_length=10, verbose_name='状态')),
                ('passwd', models.CharField(default='', max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
    ]
